[project]
name = "e-check"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.15.2",
    "fastapi[standard]>=0.115.12",
    "passlib[bcrypt]>=1.7.4",
    "psycopg[binary]>=3.2.6",
    "pydantic-settings>=2.9.1",
    "pyjwt>=2.10.1",
    "sqlalchemy>=2.0.40",
    "testcontainers[postgres]>=4.10.0",
]

[dependency-groups]
dev = [
    "anyio>=4.9.0",
    "pytest>=8.3.5",
    "pytest-clarity>=1.0.1",
    "pytest-cov>=6.1.1",
    "ruff>=0.11.7",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/e_check"]


[tool.pytest.ini_options]
pythonpath = "src"
testpaths = ["tests"]

# https://github.com/pytest-dev/pytest-cov/issues/596#issuecomment-2183411522
# https://github.com/nedbat/coveragepy/issues/1216#issuecomment-2276972265
[tool.coverage.run]
concurrency = ["greenlet", "thread"]