"""Initial models User,Check,Product,Payment

Revision ID: 82582c031f3a
Revises:
Create Date: 2025-04-27 18:52:49.794408

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from e_check.db.models import Base

# revision identifiers, used by Alembic.
revision: str = "82582c031f3a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
        sa.UniqueConstraint("username", name=op.f("uq_user_username")),
    )
    op.create_table(
        "check",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_check_user_id_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_check")),
    )
    op.create_table(
        "payment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("check_id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "cash", "cashless", name="payment_type_enum", metadata=Base.metadata
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(), nullable=False),
        sa.ForeignKeyConstraint(
            ["check_id"], ["check.id"], name=op.f("fk_payment_check_id_check")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment")),
    )
    op.create_table(
        "product",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("check_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("price", sa.Numeric(), nullable=False),
        sa.Column("quantity", sa.Numeric(), nullable=False),
        sa.ForeignKeyConstraint(
            ["check_id"], ["check.id"], name=op.f("fk_product_check_id_check")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("product")
    op.drop_table("payment")
    op.drop_table("check")
    op.drop_table("user")
    # ### end Alembic commands ###
